# docker-compose.yml
version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER= postgres
      POSTGRES_PASSWORD=postgres
      POSTGRES_DB= postgres
    ports:
      - '5432:5432' 
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
        PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db

volumes:
  db-data:
