# docker-compose.yml
version: '3.8'

services:
  
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    # env_file:
    #   - .env
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    restart: always
    # env_file:
    #   - .env
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
    ports:
      - '5432:5432' 
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
